### PR TITLE
Added coverage rule and tests

### PR DESCRIPTION
**Pull request by nomiddlename**
I'm trying to have all the external appenders with 100% test coverage, so I've added the rule and added a few more tests. I've also changed the `type` in the tests so that it points to the appender code in this repo instead of the logstashUDP appender that is still included in log4js.

@cula - I'll merge this myself, and then publish to NPM. I just wanted to make a PR so that you are aware of what I'm doing. Once I've published to NPM I'll deprecate the existing appender in log4js, and remove it from the version-3.x branch.

### CODE REVIEW

**Comment by cula** [comment]
Got it. I found the problem, So I removed '-100' from npm test to avoid UT failed. And I'll keep this in the future.

**Comment by cula** [comment]
And 
1. Nodejs 4 will be out of maintaince officially at the end of Apr 2018. So should we remove it from our support list?
2. May I use Babel to support the previous nodejs LTS versions so as to use new features in the newer nodejs version (such as version 8.x lts)?

**Comment by nomiddlename** [comment]
The plan is to remove support for node 4 in version 3 of log4js. 

I'm happy for you do whatever you want in this appender (one of the benefits of splitting them out from the core) - so feel free to experiment. I'm going to be a bit more conservative with what makes it back into the log4js core though.

**Comment by nomiddlename** [comment]
I've published this to npm. I'll deprecate the existing core one, and remove it from the version 3.x branch

**Comment by cula** [comment]
Nice. Thank you for the freedom

**Pull request merged**
